name: Run tests

on: pull_request

jobs:
  run-tests:
    strategy:
      matrix:
        go-version: [1.23.3]
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests
        run: |
          go test -v -race -count=3 -covermode=atomic ./...
